language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - mkdir src/db
install:
  - npm install
  - npm install grunt-cli -g
  - npm install istanbul
before_script:
  - node src/initdb.js
  - node src/initdata.js
  - node src/app.js &
script:
  - grunt coverage