language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - mkdir src/db
install:
  - npm install
before_script:
  - cd src
  - ls ./models
  - node initdb.js
  - node app.js
  - cd ..
script:
  - grunt test